#!/bin/sh
# vim: set ts=4 sw=4 et:

#
# Copyright (c) 2008, Novell, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#  * Neither the name of the <ORGANIZATION> nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
#
# (Licensed under the simplified BSD license)
#
# Authors: Vincent Untz <vuntz@novell.com>
#

basedir=`dirname $0`

if test "x$OBS_DISSECTOR_DIR" = "x"; then
    OBS_DISSECTOR_DIR=/tmp/obs-dissector
fi

mkdir -p $OBS_DISSECTOR_DIR

######################################
# Download latest upstream versions
# For non-GNOME:Factory, we only care about the official GNOME modules.

download_gnome_version () {
    VERSION=$1
    if test "x$1" = "x"; then
        return
    fi

    DESTFILE=$OBS_DISSECTOR_DIR/tmp/versions-gnome-$VERSION
    if test -f $DESTFILE; then
        rm -f $DESTFILE
    fi

    wget -q -nc -O $DESTFILE http://www.gnome.org/~vuntz/tmp/versions/versions-$VERSION

    # Don't use gstreamer from ftp.gnome.org -- it can be outdated
    sed -i "s/^\(desktop:gst-plugins.*\)$/# \1/g;s/^\(desktop:gstreamer:.*\)$/# \1/g" $DESTFILE
    # We don't care about mobile stuff
    sed -i "s/^\(mobile:.*\)$/# \1/g" $DESTFILE
}

download_gnome_version 2.26
download_gnome_version stable
download_gnome_version unstable
download_gnome_version extras

GNOME_FACTORY_VERSION=unstable

test -f $OBS_DISSECTOR_DIR/tmp/versions-upstream && cp $OBS_DISSECTOR_DIR/tmp/versions-upstream $OBS_DISSECTOR_DIR/tmp/versions-upstream.bak
$basedir/download-upstream-versions \
    --upstream-tarballs=$basedir/upstream-tarballs.txt \
    --upstream-limits=$basedir/upstream-limits.txt \
    --save-file=$OBS_DISSECTOR_DIR/tmp/versions-upstream \
    --only-if-old --use-old-as-fallback
if test $? -ne 0; then
    test -f cp $OBS_DISSECTOR_DIR/tmp/versions-upstream.bak && cp $OBS_DISSECTOR_DIR/tmp/versions-upstream.bak $OBS_DISSECTOR_DIR/tmp/versions-upstream
    echo "Error while checking for new upstream versions"
fi
cat $OBS_DISSECTOR_DIR/tmp/versions-gnome-$GNOME_FACTORY_VERSION \
    $OBS_DISSECTOR_DIR/tmp/versions-gnome-extras \
    $OBS_DISSECTOR_DIR/tmp/versions-upstream \
    > $OBS_DISSECTOR_DIR/tmp/versions-latest

# Check that we have everything in the match database
for i in `grep -v '^#' $OBS_DISSECTOR_DIR/tmp/versions-latest | grep ':' | cut -d ':' -f 2`; do
    re_i=`echo $i | sed 's/\+/\\\\\\+/g'`
    grep -q -E "^(# ?)?$re_i:" $basedir/upstream-packages-match.txt
    if test $? -ne 0; then
        echo $i not in $basedir/upstream-packages-match.txt
    fi
done

test -f $OBS_DISSECTOR_DIR/tmp/versions-fallback && mv $OBS_DISSECTOR_DIR/tmp/versions-fallback $OBS_DISSECTOR_DIR/tmp/versions-fallback.bak
wget -q -nc -O $OBS_DISSECTOR_DIR/tmp/versions-fallback http://www.suse.de/~meissner/factory.upstream.lst
if test $? -ne 0; then
    test -f $OBS_DISSECTOR_DIR/tmp/versions-fallback.bak && cp $OBS_DISSECTOR_DIR/tmp/versions-fallback.bak $OBS_DISSECTOR_DIR/tmp/versions-fallback
    echo "Error while checking for fallback of new upstream versions"
fi


######################################
# Check out from the build service

# We check everything out in a temporary directory.
# At the end, we'll symlink this directory to the stable directory, and
# remove the old checkout. This way, we always have a valid & working
# stable checkout.
CACHE_CO=`$basedir/obs-checkout --get-stable-directory`
DEST_CO=`$basedir/obs-checkout --get-new-directory`

OBS_CHECKOUT_ARGS="--cache-directory $CACHE_CO --destination-directory $DEST_CO"

$basedir/obs-checkout $OBS_CHECKOUT_ARGS \
    --project openSUSE:Factory \
    --devel-projects-of openSUSE:Factory \
    --metadata "parent=openSUSE:Factory" \
    --metadata "versionfile=$OBS_DISSECTOR_DIR/tmp/versions-latest" \
    || (echo "Error in obs-checkout."; exit 1)
# No version file for Moblin: we don't care about upstream there
$basedir/obs-checkout $OBS_CHECKOUT_ARGS \
    --project Moblin:Factory \
    --devel-projects-of Moblin:Factory \
    --metadata "parent=Moblin:Factory" \
    || (echo "Error in obs-checkout."; exit 1)
$basedir/obs-checkout $OBS_CHECKOUT_ARGS \
    --project openSUSE:Factory:Contrib \
    --metadata "parent=openSUSE:Factory:Contrib" \
    --metadata "versionfile=$OBS_DISSECTOR_DIR/tmp/versions-latest" \
    || (echo "Error in obs-checkout."; exit 1)
$basedir/obs-checkout $OBS_CHECKOUT_ARGS \
    --project GNOME:Contrib \
    --metadata "parent=openSUSE:Factory:Contrib" \
    --metadata "versionfile=$OBS_DISSECTOR_DIR/tmp/versions-latest" \
    || (echo "Error in obs-checkout."; exit 1)
$basedir/obs-checkout $OBS_CHECKOUT_ARGS \
    --project GNOME:STABLE:2.26 \
    --metadata "versionfile=$OBS_DISSECTOR_DIR/tmp/versions-gnome-2.26" \
    --metadata "ignore-fallback=true" \
    || (echo "Error in obs-checkout."; exit 1)

$basedir/obs-checkout --make-directory-stable "$DEST_CO"


######################################
# Get the rpmlint data
# GNOME:Factory only

# We download the rpmlint data. We keep the old version around until we're sure
# the new version is fine.
get_rpmlint () {
    PROJECT=$1
    if test "x$1" = "x"; then
        return
    fi

    if test -f rpmlint.tar.bz2; then
        rm -f rpmlint.tar.bz2
    fi
    wget -q ftp://ftp.coolice.org/rpmlint/$PROJECT/rpmlint.tar.bz2
    if test $? -eq 0; then
        if test -d $PROJECT; then
            mv $PROJECT $PROJECT.old
        fi
        tar jxf rpmlint.tar.bz2
        if test $? -ne 0 -a -d $PROJECT.old; then
            mv $PROJECT.old $PROJECT
        fi
        if test -d $PROJECT.old; then
            rm -rf $PROJECT.old
        fi

        rm -f rpmlint.tar.bz2
    fi
}

mkdir -p $OBS_DISSECTOR_DIR/tmp/rpmlint
pushd $OBS_DISSECTOR_DIR/tmp/rpmlint > /dev/null
get_rpmlint openSUSE:Factory
get_rpmlint GNOME:Factory
get_rpmlint GNOME:Contrib
popd > /dev/null


######################################
# Create the databases

$basedir/create-database --force \
    --output-database $OBS_DISSECTOR_DIR/obs.db \
    --checkout-dir $DEST_CO \
    --upstream-name $basedir/upstream-packages-match.txt \
    --upstream-versions-fallback $OBS_DISSECTOR_DIR/tmp/versions-fallback

$basedir/list-packages --output-database $OBS_DISSECTOR_DIR/packagelist.db
