#!/bin/sh

#
# Copyright (c) 2008, Novell, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#  * Neither the name of the <ORGANIZATION> nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
#
# (Licensed under the simplified BSD license)
#
# Authors: Vincent Untz <vuntz@novell.com>
#

basedir=`dirname $0`

if test "x$OBS_DISSECTOR_DIR" = "x"; then
    OBS_DISSECTOR_DIR=/tmp/obs-dissector
fi

mkdir -p $OBS_DISSECTOR_DIR

cp --force gnome-opensuse-match.txt $OBS_DISSECTOR_DIR
cp --force upstream-limits.txt $OBS_DISSECTOR_DIR
cp --force upstream-tarballs.txt $OBS_DISSECTOR_DIR

$basedir/download-gnome-versions
$basedir/download-upstream-versions --upstream-tarballs=$OBS_DISSECTOR_DIR/upstream-tarballs.txt --upstream-limits=$OBS_DISSECTOR_DIR/upstream-limits.txt  --save-file=$OBS_DISSECTOR_DIR/tmp/versions-non-fgo --only-if-old --use-old-as-fallback
# Don't use gstreamer from ftp.gnome.org -- it can be outdated
sed -i "s/^\(desktop:gst-plugins.*\)$/# \1/g;s/^\(desktop:gstreamer:.*\)$/# \1/g" $OBS_DISSECTOR_DIR/versions
# We don't care about mobile stuff
sed -i "s/^\(mobile:.*\)$/# \1/g" $OBS_DISSECTOR_DIR/versions
cat $OBS_DISSECTOR_DIR/tmp/versions-non-fgo >> $OBS_DISSECTOR_DIR/versions

# Check that we have everything in the match database.
for i in `grep -v '^#' $OBS_DISSECTOR_DIR/versions | grep ':' | cut -d ':' -f 2`; do
    re_i=`echo $i | sed 's/\+/\\\\\\+/g'`
    grep -q -E "^(# ?)?$re_i:" $OBS_DISSECTOR_DIR/gnome-opensuse-match.txt
    if test $? -ne 0; then
        echo $i not in $OBS_DISSECTOR_DIR/gnome-opensuse-match.txt
    fi
done

# We check everything out in a temporary directory.
# At the end, we'll symlink this directory to the stable directory, and
# remove the old checkout. This way, we always have a valid & working
# stable checkout.
CACHE_CO=`$basedir/obs-checkout --get-stable-directory`
DEST_CO=`$basedir/obs-checkout --get-new-directory`
$basedir/obs-checkout --cache-directory "$CACHE_CO" --destination-directory "$DEST_CO" --packages-of GNOME:Factory --project openSUSE:Factory
if test $? -ne 0; then
	echo "Error while checking out openSUSE:Factory"
	return 1
fi
$basedir/obs-checkout --cache-directory "$CACHE_CO" --destination-directory "$DEST_CO" --warn-if-not-unexpanded-link --project GNOME:Factory
if test $? -ne 0; then
	echo "Error while checking out GNOME:Factory"
	return 1
fi
echo "Development project" > $DEST_CO/GNOME:Factory/.is-devel-project
$basedir/obs-checkout --make-directory-stable "$DEST_CO"

$basedir/create-database --force --output-database $OBS_DISSECTOR_DIR/obs.db
