#!/bin/sh

TOP_DIR=`dirname $0`

if test ! -f "${TOP_DIR}/common"; then
	echo "No common infrastructure available."
	exit 1
fi

. "${TOP_DIR}/common"

# 10 minutes max
setup 600

echo starting ${PRE_CMD} "${OSC_PLUGIN_COLLAB_DIR}/server/upstream/runme"

${PRE_CMD} "${OSC_PLUGIN_COLLAB_DIR}/server/upstream/runme" -o "${OBS_CONF}" -l $LOGFILE

cleanup
