#!/bin/sh

TOP_DIR=`dirname $0`

if test ! -f "${TOP_DIR}/common"; then
	echo "No common infrastructure available."
	exit 1
fi

. "${TOP_DIR}/common"

# 1 minute max
setup 60

# Because of how git works, we have to hack around to redirect stderr to a file
# and only output it if git has a non-0 return value...

cd ${OSC_PLUGIN_COLLAB_DIR}
${PRE_CMD} git pull >> $LOGFILE 2> $LOGFILE.stderr

if test $? -ne 0 -a -f $LOGFILE.stderr; then
	cat $LOGFILE.stderr >&2
fi

rm -f $LOGFILE.stderr

cleanup
